name: CI

on:
  push: 
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Build
        uses: docker/build-push-action@729f7f49266dec5e72fe7339273d3f7e65abacd7
        with:
          context: .
          push: false
